name:CI/CD Pipeline

on:
  push:
    branches:
      -main
  pull_request:
    branches:
      main

  jobs:
    buils:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v2
        with:
          python-version: '3.x'
        
        - name:Install dependencies
          run: /
            python -pip install --upgrade pip
            pip install -r requirements.txt